disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - line_length
  - function_body_length
  - file_length
  - type_body_length
  - force_cast
  - force_try
  - function_parameter_count

opt_in_rules: # some rules are only opt-in
  - empty_count
  - closure_spacing
  - explicit_init
  - first_where
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_imports

included: # paths to include during linting. `--path` is ignored if present.
  - OpenResponses

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - OpenResponsesUITests

# configurable rules can be customized from this configuration file
cyclomatic_complexity:
  warning: 15
  error: 25

identifier_name:
  min_length: 2
  excluded:
    - id
    - URL
    - GlobalAPIKey

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)
