default_platform(:ios)

platform :ios do
  desc "Upload App Store metadata without a binary"
  lane :metadata do
    api_key = nil
    if ENV["APP_STORE_CONNECT_API_KEY_ID"] && ENV["APP_STORE_CONNECT_ISSUER_ID"] && ENV["APP_STORE_CONNECT_API_KEY_PATH"]
      api_key = app_store_connect_api_key(
        key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
        issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
        key_filepath: ENV["APP_STORE_CONNECT_API_KEY_PATH"]
      )
    end

    deliver(
      api_key: api_key,
      skip_binary_upload: true,
      skip_screenshots: ENV["DELIVER_SCREENSHOTS"] != "1",
      force: true,
      metadata_path: "fastlane/metadata",
      screenshots_path: "fastlane/screenshots",
      run_precheck_before_submit: false,
      precheck_include_in_app_purchases: false
    )
  end
end
